controllers/admin_dashboard.py
from flask import Blueprint, render_template, request, abort, flash, redirect, url_for
from flask_login import current_user, login_required
from controllers.security import role_required
from database.models import *
from datetime import datetime
from sqlalchemy import func

bp = Blueprint('admin_dashboard', __name__, url_prefix='/admin')


"""
https://patorjk.com/software/taag/#p=display&f=Electronic&t=pages

 ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄ 
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀▀▀ 
▐░▌       ▐░▌▐░▌       ▐░▌▐░▌          ▐░▌          ▐░▌          
▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄█░▌▐░▌ ▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄▄▄ 
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░▌▐░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░▌ ▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀█░▌
▐░▌          ▐░▌       ▐░▌▐░▌       ▐░▌▐░▌                    ▐░▌
▐░▌          ▐░▌       ▐░▌▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄█░▌
▐░▌          ▐░▌       ▐░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
 ▀            ▀         ▀  ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀ 

"""


@bp.route('/dashboard')
@login_required
@role_required(UserRole.ADMIN)
def home():
  customers = db.session.query(Customer).all()
  professionals = db.session.query(Professional).all()
  service_types = db.session.query(ServiceType).all()
  services = db.session.query(Service).all()
  bookings = db.session.query(Booking).all()
  cities = db.session.query(City).all()

  return render_template('dashboard/admin/home.html',
                         customers=customers,
                         professionals=professionals,
                         service_types=service_types,
                         services=services,
                         bookings=bookings,
                         cities=cities
                         )


@bp.route('/search')
@login_required
@role_required(UserRole.ADMIN)
def search():
  cities = db.session.query(City).all()
  service_types = db.session.query(ServiceType).all()
  return render_template('dashboard/admin/search.html',
                         cities=cities,
                         service_types=service_types
                         )


@bp.route('/search-results')
@login_required
@role_required(UserRole.ADMIN)
def search_results():
  role = request.args.get('role')
  name = request.args.get('name').strip()
  address = request.args.get('address').strip()
  postal_code = request.args.get('postal_code').strip()
  phone_number = request.args.get('phone_number').strip()
  city_id = request.args.get('city')
  service_type_id = request.args.get('service_type_id')

  query = None
  if role == 'customer':
    query = db.session.query(Customer).join(User).filter(User.role == UserRole.CUSTOMER)
  elif role == 'professional':
    query = db.session.query(Professional).join(User).filter(User.role == UserRole.PROFESSIONAL)

  if name:
    query = query.filter(User.name.ilike(f"%{name}%"))
  if address:
    query = query.filter(User.address.ilike(f"%{address}%"))
  if postal_code:
    query = query.filter(User.postal_code.ilike(f"%{postal_code}%"))
  if city_id:
    query = query.filter(User.city_id == city_id)
  if phone_number:
    query = query.filter(User.phone_number.ilike(f"%{phone_number}%"))
  if service_type_id:
    query = query.filter(Professional.service_type_id == service_type_id)

  results = query.all()
  return render_template('dashboard/admin/search_results.html',
                         role=role,
                         results=results)


@bp.route('/summary')
@login_required
@role_required(UserRole.ADMIN)
def summary():
  total_bookings = db.session.query(Booking).count()

  # count ratings by 1-5 stars with percentages
  ratings_count = db.session.query(
      Booking.review_stars,
      func.count(Booking.id)
  ).filter(
      Booking.review_stars.isnot(None)
  ).group_by(
      Booking.review_stars
  ).all()

  rated_bookings = 0
  for star, count in ratings_count:
    rated_bookings += count

  ratings_dict = [
      {
          "stars": star,
          "count": count,
          "percentage": (count / rated_bookings * 100) if rated_bookings else 0
      }
      for star, count in ratings_count
  ]

  # ensure all 1-5 stars are present
  for star in range(1, 6):
    if not any(r["stars"] == star for r in ratings_dict):
      ratings_dict.append({"stars": star, "count": 0, "percentage": 0})
  ratings_dict.sort(key=lambda r: r["stars"])

  # count bookings by status with percentages
  booking_status_counts = db.session.query(
      Booking.status,
      func.count(Booking.id)
  ).group_by(Booking.status).all()

  status_dict = [
      {
          "status": status.name.title(),
          "count": count,
          "percentage": (count / total_bookings * 100) if total_bookings else 0
      }
      for status, count in booking_status_counts
  ]

  # ensure all statuses are present
  for status in BookingStatus:
    if not any(s["status"] == status.name.title() for s in status_dict):
      status_dict.append({"status": status.name.title(), "count": 0, "percentage": 0})
  status_dict.sort(key=lambda s: s["status"])

  # today's bookings count
  today = datetime.today().date()
  today_created = db.session.query(Booking).filter(
      func.date(Booking.created_on) == today
  ).count()
  today_assigned = db.session.query(Booking).filter(
      func.date(Booking.assigned_on) == today
  ).count()
  today_closed = db.session.query(Booking).filter(
      func.date(Booking.closed_on) == today
  ).count()

  return render_template(
      'dashboard/admin/summary.html',
      ratings_dict=ratings_dict,
      status_dict=status_dict,
      total_bookings=total_bookings,
      today_created=today_created,
      today_assigned=today_assigned,
      today_closed=today_closed
  )


"""
https://patorjk.com/software/taag/#p=display&f=Electronic&t=rpcs

 ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄ 
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀▀▀ 
▐░▌       ▐░▌▐░▌       ▐░▌▐░▌          ▐░▌          
▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄█░▌▐░▌          ▐░█▄▄▄▄▄▄▄▄▄ 
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░▌          ▐░░░░░░░░░░░▌
▐░█▀▀▀▀█░█▀▀ ▐░█▀▀▀▀▀▀▀▀▀ ▐░▌           ▀▀▀▀▀▀▀▀▀█░▌
▐░▌     ▐░▌  ▐░▌          ▐░▌                    ▐░▌
▐░▌      ▐░▌ ▐░▌          ▐░█▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄█░▌
▐░▌       ▐░▌▐░▌          ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
 ▀         ▀  ▀            ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀ 
                                                    
"""


@bp.route('/block_user/<int:user_id>')
@login_required
@role_required(UserRole.ADMIN)
def block_user(user_id):
  user = User.query.filter_by(id=user_id).first()
  user.is_blocked = True
  db.session.commit()

  flash(f'{user.role.name.capitalize()} "{user.name}" has been blocked.', 'success')
  anchor = 'professionals_table' if user.role.name == 'PROFESSIONAL' \
      else 'customers_table'
  return redirect(url_for('admin_dashboard.home', _anchor=anchor))


@bp.route('/unblock_user/<int:user_id>')
@login_required
@role_required(UserRole.ADMIN)
def unblock_user(user_id):
  user = User.query.filter_by(id=user_id).first()
  user.is_blocked = False
  db.session.commit()

  flash(f'{user.role.name.capitalize()} "{user.name}" has been unblocked.', 'success')
  anchor = 'professionals_table' if user.role.name == 'PROFESSIONAL' \
      else 'customers_table'
  return redirect(url_for('admin_dashboard.home', _anchor=anchor))


@bp.route('/verify_professional/<int:professional_id>')
@login_required
@role_required(UserRole.ADMIN)
def verify_professional(professional_id):
  professional = Professional.query.filter_by(id=professional_id).first()
  professional.is_verified = True
  db.session.commit()

  flash(f'Professional {professional.user.name} has been verified.', 'success')
  return redirect(url_for('admin_dashboard.home', _anchor='professionals_table'))


@bp.route('/update_service/<int:service_id>', methods=['GET', 'POST'])
@login_required
@role_required(UserRole.ADMIN)
def update_service(service_id):
  service = Service.query.filter_by(id=service_id).first()

  if request.method == 'POST':
    service.name = request.form.get('name')
    service.price = request.form.get('price')
    service.description = request.form.get('description')
    service.service_type_id = request.form.get('service_type')
    db.session.commit()
    flash(f'Service "{service.name}" has been updated.', 'success')
    return redirect(url_for('admin_dashboard.home', _anchor='services_table'))

  service_types = ServiceType.query.all()
  return render_template(
      'dashboard/admin/update_service.html',
      service=service,
      service_types=service_types,
  )


@bp.route('/delete_service/<int:service_id>')
@login_required
@role_required(UserRole.ADMIN)
def delete_service(service_id):
  service = Service.query.filter_by(id=service_id).first()
  db.session.delete(service)
  db.session.commit()

  flash(f'Service "{service.name}" has been deleted.', 'success')
  return redirect(url_for('admin_dashboard.home', _anchor='services_table'))


@bp.route('/create_service', methods=['GET', 'POST'])
@login_required
@role_required(UserRole.ADMIN)
def create_service():
  if request.method == 'POST':
    service_name = request.form.get('name')
    service_type_id = request.form.get('service_type')
    price = request.form.get('price')
    description = request.form.get('description')
    new_service = Service(
        name=service_name,
        service_type_id=service_type_id,
        price=price,
        description=description
    )
    db.session.add(new_service)
    db.session.commit()
    flash(f'Service "{new_service.name}" has been created.', 'success')
    return redirect(url_for('admin_dashboard.home', _anchor='services_table'))

  service_types = ServiceType.query.all()
  return render_template('dashboard/admin/create_service.html', service_types=service_types)

templates/dashboard/admin/create_city.html
{% extends 'dashboard/common/base.html' %}

<!-- == -->
{% block title %}Create New City{% endblock %}

<!-- == -->
{% block main %}
  <div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title text-center mb-4">Create New City</h2>
            <form method="POST" action="{{ url_for('admin_dashboard.create_city') }}">
              <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name" required />
              </div>
              <div class="mb-3">
                <label for="state_code" class="form-label">State Code</label>
                <select class="form-control" id="state_code" name="state_code" required>
                  {% for state_code, state_name in states %}
                    <option value="{{ state_code }}">{{ state_code }} ({{ state_name }})</option>
                  {% endfor %}
                </select>
              </div>
              <button type="submit" class="btn btn-primary">Create</button>
              <a href="{{ url_for('admin_dashboard.home') }}"
                 class="btn btn-secondary">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/admin/create_service.html
{% extends 'dashboard/common/base.html' %}

<!-- == -->
{% block title %}Create New Service{% endblock %}

<!-- == -->
{% block main %}
  <div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title text-center mb-4">Create New Service</h2>
            <form method="POST"
                  action="{{ url_for('admin_dashboard.create_service') }}">
              <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name" required />
              </div>
              <div class="mb-3">
                <label for="service_type" class="form-label">Service Type</label>
                <select class="form-control" id="service_type" name="service_type" required>
                  {% for service_type in service_types %}
                    <option value="{{ service_type.id }}">{{ service_type.name }}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="mb-3">
                <label for="price" class="form-label">Price</label>
                <input type="number" class="form-control" id="price" name="price" required />
              </div>
              <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <textarea class="form-control" id="description" name="description" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Create</button>
              <a href="{{ url_for('admin_dashboard.home') }}"
                 class="btn btn-secondary">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/admin/create_service_type.html
{% extends 'dashboard/common/base.html' %}

<!-- == -->
{% block title %}Create New Service Type{% endblock %}

<!-- == -->
{% block main %}
  <div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title text-center mb-4">Create New Service Type</h2>
            <form method="POST"
                  action="{{ url_for('admin_dashboard.create_service_type') }}">
              <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name" required />
              </div>
              <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <textarea class="form-control" id="description" name="description" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Create</button>
              <a href="{{ url_for('admin_dashboard.home') }}"
                 class="btn btn-secondary">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/admin/home.html
{% extends 'dashboard/common/base.html' %}

{% set active_page = "home" %}

{% block title %}Home{% endblock %}

{% block header %}<h1>Welcome, {{ current_user.name }}</h1>{% endblock %}

{% block main %}
  <section class="container my-5" id="customers_table">
    <h2 class="py-4 pb-2">Manage Customers</h2>
    <p class="my-4 text-muted">
      Here you can view and manage the registered customers.
    </p>
    <div>{% include 'dashboard/common/partials/customers_table.html' %}</div>
  </section>

  <section class="container my-5" id="professionals_table">
    <h2 class="py-4 pb-2">Manage Professionals</h2>
    <p class="my-4 text-muted">
      View and manage the professionals registered in the system.
    </p>
    <div>{% include 'dashboard/common/partials/professionals_table.html' %}</div>
  </section>

  <section class="container my-5" id="services_table">
    <h2 class="py-4 pb-2">Manage Services</h2>
    <p class="my-4 text-muted">
      Manage the services available for customers to book.
    </p>
    <div>{% include 'dashboard/common/partials/services_table.html' %}</div>
    <a href="{{ url_for('admin_dashboard.create_service') }}"
       class="btn btn-primary mt-3">Create New Service</a>
  </section>

  <section class="container my-5" id="service_types_table">
    <h2 class="py-4 pb-2">Manage Service Types</h2>
    <p class="my-4 text-muted">
      Create and manage different types of services offered.
    </p>
    <div>{% include 'dashboard/common/partials/service_types_table.html' %}</div>
    <a href="{{ url_for('admin_dashboard.create_service_type') }}"
       class="btn btn-primary mt-3">Create New Service Type</a>
  </section>

  <section class="container my-5" id="cities_table">
    <h2 class="py-4 pb-2">Manage Cities</h2>
    <p class="my-4 text-muted">Manage the cities where services are available.</p>
    <div>{% include 'dashboard/common/partials/cities_table.html' %}</div>
    <a href="{{ url_for('admin_dashboard.create_city') }}"
       class="btn btn-primary mt-3">Create New City</a>
  </section>

  <section class="container my-5" id="bookings_table">
    <h2 class="py-4 pb-2">Manage Bookings</h2>
    <p class="my-4 text-muted">View and manage all bookings on the platform.</p>
    {% set table_id = "all" %}
    {% set table_type = "all" %}
    <div>{% include 'dashboard/common/partials/bookings_table.html' %}</div>
  </section>
{% endblock %}

{% block footer %}
  <script>
      $(document).ready(function() {
          var tableIds = ['customersTable', 'professionalsTable', 'servicesTable', 'serviceTypesTable', 'citiesTable', 'bookingsTable_all'];
          var anchors = [
              '#customers_table',
              '#professionals_table',
              '#services_table',
              '#service_types_table',
              '#cities_table',
              '#bookings_table'
          ];
          initializeTablesAndAnchors(tableIds, anchors);
      });
  </script>
{% endblock %}

templates/dashboard/admin/search.html
{% extends 'dashboard/common/base.html' %}

<!-- == -->
{% set active_page = "search" %}

<!-- == -->
{% block title %}Search{% endblock %}

<!-- == -->
{% block header %}<h1>Search</h1>{% endblock %}

<!-- == -->
{% block main %}
  <style>
      .hidden {
          display: none;
      }
  </style>

  <!-- search form -->
  <div class="container my-5">
    <form method="GET"
          action="{{ url_for('admin_dashboard.search_results') }}"
          class="row g-3">
      <!-- select customer/professional -->
      <div class="col-md-6 col-lg-4 mb-2">
        <label for="role" class="form-label">Search For</label>
        <select id="role" name="role" class="form-select" required>
          <option value="customer">Customer</option>
          <option value="professional">Professional</option>
        </select>
        <p class="mt-2 my-4 text-muted">
          Select whether to search for a customer or professional.
        </p>
      </div>

      <!-- service type -->
      <div class="hidden col-md-6 col-lg-4 mb-2" id="serviceTypeField">
        <label for="service_type" class="form-label">Service Type</label>
        <select id="service_type" name="service_type_id" class="form-select">
          <option value="" selected>Choose Service Type</option>
          {% for service_type in service_types %}
            <option value="{{ service_type.id }}">{{ service_type.name }}</option>
          {% endfor %}
        </select>
        <p class="mt-2 my-4 text-muted">
          Select the relevant service type for professionals.
        </p>
      </div>

      <!-- name -->
      <div class="col-md-6 col-lg-4 mb-2">
        <label for="name" class="form-label">Name</label>
        <input type="text" id="name" name="name" class="form-control" />
        <p class="mt-2 my-4 text-muted">Search by name (partial match allowed).</p>
      </div>

      <!-- address -->
      <div class="col-md-6 col-lg-4 mb-2">
        <label for="address" class="form-label">Address</label>
        <input type="text" id="address" name="address" class="form-control" />
        <p class="mt-2 my-4 text-muted">Search by address (partial match allowed).</p>
      </div>

      <!-- postal code -->
      <div class="col-md-6 col-lg-4 mb-2">
        <label for="postal_code" class="form-label">Postal Code</label>
        <input type="text" id="postal_code" name="postal_code" class="form-control" />
        <p class="mt-2 my-4 text-muted">
          Search by postal code (partial match allowed).
        </p>
      </div>

      <!-- phone number -->
      <div class="col-md-6 col-lg-4 mb-2">
        <label for="phone_number" class="form-label">Phone Number</label>
        <input type="text"
               id="phone_number"
               name="phone_number"
               class="form-control" />
        <p class="mt-2 my-4 text-muted">
          Search by phone number (partial match allowed).
        </p>
      </div>

      <!-- city -->
      <div class="col-md-6 col-lg-4 mb-2">
        <label for="city" class="form-label">City</label>
        <select id="city" name="city" class="form-select">
          <option value="" selected>All Cities</option>
          {% for city in cities %}
            <option value="{{ city.id }}">{{ city.name }}</option>
          {% endfor %}
        </select>
        <p class="mt-2 my-4 text-muted">Select a city to narrow your search.</p>
      </div>

      <!-- submit button -->
      <div class="col-12">
        <button type="submit" class="btn btn-primary">Search</button>
        <button type="reset" class="btn btn-secondary ms-3">Clear</button>
      </div>
    </form>
  </div>

  <script>
      document.addEventListener('DOMContentLoaded', function() {
          const roleSelect = document.getElementById('role');
          const serviceTypeField = document.getElementById('serviceTypeField');

          roleSelect.addEventListener('change', function() {
              if (roleSelect.value === 'professional') {
                  serviceTypeField.classList.remove('hidden');
              } else {
                  serviceTypeField.classList.add('hidden');
              }
          });
      });
  </script>
{% endblock %}

templates/dashboard/admin/search_results.html
{% extends 'dashboard/common/base.html' %}

{% set active_page = "search" %}

{% block title %}Search Results{% endblock %}

{% block header %}<h1>Search Results</h1>{% endblock %}

{% block main %}
  <div class="container my-5">
    {% if results|length == 0 %}
      <p>No results found for the given search criteria.</p>

    {% elif role == 'customer' %}
      {% set customers = results %}
      <div class="container my-5" id="customers_table">
        {% include 'dashboard/common/partials/customers_table.html' %}
      </div>

    {% elif role == 'professional' %}
      {% set professionals = results %}
      <div class="container my-5" id="professionals_table">
        {% include 'dashboard/common/partials/professionals_table.html' %}
      </div>
    {% endif %}
  </div>

  <script>
      $(document).ready(function() {
          var tableIds = ['customersTable', 'professionalsTable'];
          var anchors = [
              '#customers_table',
              '#professionals_table',
          ];
          tableIds.forEach(function(tableId) {
              if ($('#' + tableId).length) {
                  $('#' + tableId).DataTable();
              }
          });
          anchors.forEach(function(id) {
              var targetContainer = $(id);
              if (targetContainer.length) {
                  targetContainer.find('.collapse').collapse('show');
              }
          });
      })
  </script>
{% endblock %}

templates/dashboard/admin/summary.html
{% extends 'dashboard/common/base.html' %}

{% set active_page = "summary" %}

{% block title %}Summary{% endblock %}

{% block header %}<h1>Summary</h1>{% endblock %}

{% block main %}
  <!-- 🎯 chart.js -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

  <div class="container my-5">
    <!-- 🎯 today's bookings -->
    <h3 class="mt-4">Today's Bookings</h3>
    <p class="my-4 text-muted">
      Below is the summary of bookings opened, assigned, and closed today.
    </p>
    <ul class="list-unstyled mb-4">
      <li>
        <span class="badge border fs-5 my-2">Open: {{ today_created }}</span>
      </li>
      <li>
        <span class="badge border fs-5 my-2">Assigned: {{ today_assigned }}</span>
      </li>
      <li>
        <span class="badge border fs-5 my-2">Closed: {{ today_closed }}</span>
      </li>
    </ul>
  </div>

  <div class="container my-5">
    <!-- 🎯 ratings breakdown -->
    <h3>Ratings Breakdown (1-5 Stars)</h3>
    <p class="my-4 text-muted">Here is the detailed breakdown of ratings.</p>
    {% include 'dashboard/common/partials/ratings_breakdown.html' %}
  </div>

  <div class="container my-5">
    <!-- 🎯 status breakdown -->
    <h3>Booking Status Breakdown</h3>
    <p class="my-4 text-muted">
      Here is the detailed overview of booking status distribution.
    </p>
    {% include 'dashboard/common/partials/status_breakdown.html' %}
  </div>

{% endblock %}

templates/dashboard/admin/update_service.html
{% extends 'dashboard/common/base.html' %}

<!-- == -->
{% block title %}Update Service{% endblock %}

<!-- == -->
{% block main %}
  <div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title text-center mb-4">Update Service</h2>
            <form method="POST"
                  action="{{ url_for('admin_dashboard.update_service', service_id=service.id) }}">
              <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text"
                       class="form-control"
                       id="name"
                       name="name"
                       value="{{ service.name }}"
                       required />
              </div>
              <div class="mb-3">
                <label for="service_type" class="form-label">Service Type</label>
                <select class="form-control" id="service_type" name="service_type" required>
                  {% for service_type in service_types %}
                    <!-- == -->
                    {% if service.service_type_id == service_type.id %}
                      <option value="{{ service_type.id }}" selected>{{ service_type.name }}</option>
                    {% else %}
                      <option value="{{ service_type.id }}">{{ service_type.name }}</option>
                    {% endif %}
                    <!-- == -->
                  {% endfor %}
                </select>
              </div>
              <div class="mb-3">
                <label for="price" class="form-label">Price</label>
                <input type="number"
                       class="form-control"
                       id="price"
                       name="price"
                       value="{{ service.price }}"
                       required />
              </div>
              <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <textarea class="form-control" id="description" name="description" rows="3">
{{ service.description }}</textarea>
              </div>
              <button type="submit" class="btn btn-primary">Update</button>
              <a href="{{ url_for('admin_dashboard.home') }}"
                 class="btn btn-secondary">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}